In [1]:
# Q1. What is a database? Differentiate between SQL and NoSQL databases.

# Answer:
# A database is an organized collection of data that can be easily accessed, managed, and updated. 
# It allows for the storage, retrieval, and manipulation of data efficiently.

# **SQL Databases:**
# - SQL (Structured Query Language) databases are relational databases that use a predefined schema to structure data.
# - Examples: MySQL, PostgreSQL, Oracle, SQL Server.
# - Data is stored in tables with rows and columns, and relationships between data are established using foreign keys.
# - SQL databases are suitable for complex queries and transactions.

# **NoSQL Databases:**
# - NoSQL (Not Only SQL) databases are non-relational and can handle a wide variety of data models like document, 
#   key-value, column-family, and graph formats.
# - Examples: MongoDB, Cassandra, Redis, CouchDB.
# - They are schema-less, meaning they can handle unstructured data and are more flexible.
# - NoSQL databases are better suited for handling large volumes of distributed data and can scale horizontally more easily.

In [2]:
# Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

# Answer:
# **DDL (Data Definition Language):** DDL is a subset of SQL used to define and manage database structures like tables, indexes, and schemas.

# - **CREATE:** Used to create a new table, database, or other database objects.
# Example:
# ```sql
# CREATE TABLE Students (
#     StudentID INT PRIMARY KEY,
#     Name VARCHAR(100),
#     Age INT
# );
# ```

# - **DROP:** Used to delete a table or database.
# Example:
# ```sql
# DROP TABLE Students;
# ```

# - **ALTER:** Used to modify the structure of an existing table, such as adding or dropping columns.
# Example:
# ```sql
# ALTER TABLE Students ADD COLUMN Address VARCHAR(255);
# ```

# - **TRUNCATE:** Used to remove all records from a table but keep the structure intact.
# Example:
# ```sql
# TRUNCATE TABLE Students;
# ```

In [3]:
# Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

# Answer:
# **DML (Data Manipulation Language):** DML is a subset of SQL used to manipulate data within existing database tables.

# - **INSERT:** Used to add new records to a table.
# Example:
# ```sql
# INSERT INTO Students (StudentID, Name, Age) VALUES (1, 'John Doe', 20);
# ```

# - **UPDATE:** Used to modify existing records in a table.
# Example:
# ```sql
# UPDATE Students SET Age = 21 WHERE StudentID = 1;
# ```

# - **DELETE:** Used to remove records from a table.
# Example:
# ```sql
# DELETE FROM Students WHERE StudentID = 1;
# ```

In [4]:
# Q4. What is DQL? Explain SELECT with an example.

# Answer:
# **DQL (Data Query Language):** DQL is a subset of SQL used to query and retrieve data from a database.

# - **SELECT:** The SELECT statement is used to fetch data from a database. 
#   You can specify the columns you want to retrieve, and use conditions to filter the data.
# Example:
# ```sql
# SELECT Name, Age FROM Students WHERE Age > 18;
# ```

In [5]:
# Q5. Explain Primary Key and Foreign Key.

# Answer:
# - **Primary Key:** A primary key is a column or a set of columns in a table that uniquely identifies each row in that table. 
#   The values in the primary key column(s) must be unique and cannot be NULL.
# Example:
# ```sql
# CREATE TABLE Students (
#     StudentID INT PRIMARY KEY,
#     Name VARCHAR(100)
# );
# ```

# - **Foreign Key:** A foreign key is a column or a set of columns in a table that establishes a link between the data in two tables. 
#   It refers to the primary key in another table, ensuring referential integrity.
# Example:
# ```sql
# CREATE TABLE Enrollments (
#     EnrollmentID INT PRIMARY KEY,
#     StudentID INT,
#     FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
# );
# ```

# Q6. Write a Python code to connect MySQL to Python. Explain the cursor() and execute() method.

# Answer:
import mysql.connector

# Connecting to MySQL
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="school"
)

# Creating a cursor object
cursor = connection.cursor()

# **cursor():** The cursor() method is used to create a cursor object that allows you to execute SQL queries 
# and fetch the results. It's like a pointer that helps to manage the context of a fetch operation.

# **execute():** The execute() method is used to execute the SQL query provided as a string. 
# It can be used to run DDL, DML, and DQL queries.
cursor.execute("SELECT * FROM Students")

# Fetching all rows from the executed query
results = cursor.fetchall()
for row in results:
    print(row)

# Closing the connection
connection.close()

In [7]:
# Q7. Give the order of execution of SQL clauses in an SQL query.

# Answer:
# The order of execution of SQL clauses in a query is as follows:
# 1. **FROM:** Determines the source tables.
# 2. **JOIN:** Combines data from multiple tables.
# 3. **WHERE:** Filters rows based on a condition.
# 4. **GROUP BY:** Groups rows sharing a property so aggregate functions can be applied.
# 5. **HAVING:** Filters groups based on a condition.
# 6. **SELECT:** Selects the columns to be displayed.
# 7. **ORDER BY:** Orders the result set.
# 8. **LIMIT/OFFSET:** Limits the number of rows returned.